env: dev
datasource:
  host: localhost:5432
  database: review_service_db
  username: ${DATASOURCE_USERNAME}
  password: ${DATASOURCE_PASSWORD}
http_server:
  host: 0.0.0.0
  port: 8080
  timeout: 4s
  idle_timeout: 30s