env: dev
datasource:
  host: localhost
  port: 5432
  database: reviewer_db
  username: cassidal
  password: A0me_Itin0se_002_016
  timeout: 5s
http_server:
  host: 0.0.0.0
  port: 8080
  timeout: 4s
  idle_timeout: 30s