env: dev
datasource:
  host: localhost
  port: 5432
  database: reviewer_db
  username: someusername
  password: somepassword
  timeout: 5s
http_server:
  host: 0.0.0.0
  port: 8080
  timeout: 4s
  idle_timeout: 30s